import React from "react";
import { FaLightbulb } from "react-icons/fa";
import { FiAlertCircle } from "react-icons/fi";
import { theme } from "../../styles/theme";

/**
 * AI Suggestions Component
 *
 * Displays personalized suggestions for resume improvement
 *
 * @param {Array} suggestions - Array of suggestion strings
 */
const Suggestions = ({ suggestions }) => {
  if (!suggestions || suggestions.length === 0) {
    return null;
  }

  const containerStyle = {
    marginTop: theme.spacing.xl,
  };

  const titleStyle = {
    fontSize: "24px",
    fontWeight: "600",
    color: theme.colors.text,
    marginBottom: theme.spacing.lg,
    display: "flex",
    alignItems: "center",
    gap: theme.spacing.sm,
  };

  const suggestionItemStyle = {
    padding: theme.spacing.lg,
    marginBottom: theme.spacing.md,
    backgroundColor: theme.colors.backgroundAlt,
    borderLeft: `4px solid ${theme.colors.primary}`,
    borderRadius: theme.radius.md,
    display: "flex",
    gap: theme.spacing.md,
  };

  const iconContainerStyle = {
    fontSize: "24px",
    color: theme.colors.primary,
    flexShrink: 0,
  };

  const textStyle = {
    fontSize: "16px",
    lineHeight: "1.6",
    color: theme.colors.text,
    flex: 1,
  };

  return (
    <div style={containerStyle}>
      <h3 style={titleStyle}>
        <FaLightbulb style={{ color: theme.colors.warning }} />
        AI-Powered Suggestions
      </h3>

      <div>
        {suggestions.map((suggestion, index) => (
          <div key={index} style={suggestionItemStyle}>
            <div style={iconContainerStyle}>
              <FiAlertCircle />
            </div>
            <div style={textStyle}>{suggestion}</div>
          </div>
        ))}
      </div>

      <div
        style={{
          marginTop: theme.spacing.lg,
          padding: theme.spacing.md,
          backgroundColor: "#F0F0F0",
          borderRadius: theme.radius.md,
          fontSize: "14px",
          color: theme.colors.textLight,
        }}
      >
        💡 <strong>Pro Tip:</strong> These suggestions are generated by AI based on
        industry best practices and ATS (Applicant Tracking System) requirements.
      </div>
    </div>
  );
};

export default Suggestions;
